fix: make gene optional param for converting genomic coords as long a…
GenomicMedLab/cool-seq-tool pull request #370
Opened 2024-09-25 17:53 UTC by katiestahl

…s tx is provided

2024-09-25 17:57 UTC, jarbesfeld submitted a review, later dismissed

2024-09-25 18:51 UTC, korikuzma requested changes

2024-09-25 18:51 UTC, korikuzma commented on tests/mappers/test_exon_genomic_coords.py
> +    assert resp.errors[0] == "`gene` or `transcipt` must be provided"
```suggestion
    assert resp.errors[0] == "Must provide either `gene` or `transcript`"
```

2024-09-25 18:51 UTC, korikuzma commented on tests/mappers/test_exon_genomic_coords.py
Tests are failing on my end. Are they passing on yours @katiestahl and @jarbesfeld ?

2024-09-25 18:59 UTC, jarbesfeld commented on tests/mappers/test_exon_genomic_coords.py
@korikuzma I think we'll need to go back and add a query for UTA that returns the gene symbol associated with a transcript (when the user does not provide the transcript initially)

2024-09-25 19:08 UTC, katiestahl commented on tests/mappers/test_exon_genomic_coords.py
@korikuzma oops, I have no idea what happened here. It was failing earlier and then I could've sworn it passed but is now failing again. There's another case failing even after fixing the error message since the gene is not getting resolved. I think Jeremy is right and that we'll need to resolve the gene if the user doesn't provide it (and I think that's what's causing this failing test as well)

2024-09-25 21:24 UTC, jarbesfeld approved these changes

2024-09-26 11:11 UTC, korikuzma requested changes
One minor change to docstring, but otherwise looks good!

2024-09-26 11:11 UTC, korikuzma commented on src/cool_seq_tool/mappers/exon_genomic_coords.py
> +        """Get gene given a transcript and position.
```suggestion
        """Get gene given a transcript.
```

2024-09-26 14:37 UTC, korikuzma approved these changes

2024-09-26 14:42 UTC, merged