Expect user to supply correctly formatted gene symbol
GenomicMedLab/cool-seq-tool pull request #375
Opened 2024-10-28 18:05 UTC by jarbesfeld

closes #374

2024-10-28 18:08 UTC, jsstevenson commented
make sure to give this a conventional commit prefix. I'm not sure if it represents a breaking change?

2024-10-29 11:01 UTC, korikuzma requested changes
Tests aren't passing. You likely need to update UTA queries to do case insensitive searches on genes.

2024-10-29 13:09 UTC, korikuzma approved these changes

2024-10-29 13:10 UTC, jarbesfeld commented
@jsstevenson Do you want to review again or is this good to merge?

2024-10-29 13:30 UTC, jsstevenson approved these changes

2024-10-29 13:38 UTC, merged