fix!: Add support for residue coords + refactor offset calculation
GenomicMedLab/cool-seq-tool pull request #384
Opened 2024-12-04 14:56 UTC by jarbesfeld

closes #383 

- This PR includes a refactor of the exon offset calculation to make this step more efficient and understandable
- This PR also includes support for residue coordinates. The fusion callers I've been working with output residue-coordinates, so when the offset is computed with respect to `alt_start_i`, the genomic position must be reduced by 1 as the exon boundaries provided by UTA are inter-residue coordinates. This adjustment is not needed however when the offset is computed using the genomic coordinate in `alt_end_i`

2024-12-09 13:51 UTC, korikuzma requested changes

2024-12-09 14:36 UTC, korikuzma approved these changes
Code seems good to me. Relying on @ahwagner to confirm logic makes sense.

2025-01-02 16:37 UTC, jarbesfeld commented
@korikuzma Requesting another review. Updated changes include addressing #389. I'm stuck on correcting the liftover logic to ensure that we are only running when we know a coordinate does not come from GRCh38 (commented out a test [here](https://github.com/GenomicMedLab/cool-seq-tool/blob/issue-383/tests/mappers/test_exon_genomic_coords.py#L1440)

2025-01-03 14:44 UTC, korikuzma requested changes
Quick initial review. I'm going to have to take more time to review the changes.

2025-01-03 14:44 UTC, korikuzma commented on src/cool_seq_tool/mappers/exon_genomic_coords.py
> +        if not genomic_ac:
Will need to remove the new line above
```suggestion
        else:
```

2025-01-03 14:44 UTC, korikuzma commented on src/cool_seq_tool/mappers/exon_genomic_coords.py
> +            return GenomicTxSeg(errors=["`gene` or `transcript` must be provided"])
It'd be nice to have better error handling at some point

2025-01-03 15:41 UTC, jarbesfeld commented on src/cool_seq_tool/mappers/exon_genomic_coords.py
> +            return GenomicTxSeg(errors=["`gene` or `transcript` must be provided"])
I agree. Is there a similar way we handle errors in our other apps?

2025-01-06 17:25 UTC, korikuzma commented on src/cool_seq_tool/mappers/exon_genomic_coords.py
> +            return GenomicTxSeg(errors=["`gene` or `transcript` must be provided"])
We can address in #161

2025-01-06 18:44 UTC, korikuzma commented on src/cool_seq_tool/mappers/exon_genomic_coords.py
>          :param coordinate_type: Coordinate type for ``seg_start_genomic`` and
@jarbesfeld this wasn't updated in this branch

2025-01-06 18:44 UTC, korikuzma commented on src/cool_seq_tool/mappers/exon_genomic_coords.py
> +        if not genomic_ac:
@jarbesfeld this wasn't updated in this branch

2025-01-06 19:36 UTC, korikuzma requested changes

2025-01-06 19:36 UTC, korikuzma commented on src/cool_seq_tool/mappers/exon_genomic_coords.py
> +            gene = _gene
It's probably best to move this section immediately after we get a `transcript`. That way we can fail fast

2025-01-06 19:36 UTC, korikuzma commented on src/cool_seq_tool/mappers/exon_genomic_coords.py
>          gene will be returned.
Docstring needs to be updated

2025-01-06 19:36 UTC, korikuzma commented on src/cool_seq_tool/mappers/exon_genomic_coords.py
> +        :param gene: A gene symbol
Does it no longer have to be HGNC gene symbol? (See other docstrings)

2025-01-06 19:36 UTC, korikuzma commented on src/cool_seq_tool/mappers/exon_genomic_coords.py
> -            return GenomicTxSeg(errors=[err_msg])
So I'm kind of confused on the purpose of this helper method. It seems like some of the work already exists in `_genomic_to_tx_segment`?

2025-01-06 20:27 UTC, jarbesfeld commented on src/cool_seq_tool/mappers/exon_genomic_coords.py
> -            return GenomicTxSeg(errors=[err_msg])
I agree. I'm going to look at this method to see if I can remove any duplicate code

2025-01-07 15:55 UTC, korikuzma requested changes

2025-01-07 15:55 UTC, korikuzma commented on tests/mappers/test_exon_genomic_coords.py
> +    assert resp.errors == ["dummy gene does not exist in UTA"]
Similar format as above

2025-01-07 16:56 UTC, jarbesfeld commented on tests/mappers/test_exon_genomic_coords.py
> +    inputs = {"gene": "WEE1", "chromosome": "11", "seg_end_genomic": 9588449}
This is due to a fix I'm making in #391. With these parameters, the method cannot accurately determine whether the coordinate comes from GRCh37 or GRCh38 (it assumes the coordinate is from GRCh38). Since the method in it's current state assumes the input is from GRCh38, I changed the coordinate to be a GRCh38 coordinate.

2025-01-07 17:34 UTC, korikuzma requested changes
Small thing

2025-01-07 17:34 UTC, korikuzma commented on src/cool_seq_tool/mappers/exon_genomic_coords.py
> +                errors=[f"Transcript does not exist in UTA: {transcript}"]
```suggestion
                errors=[f"No exons found given transcript: {transcript}"]
```

2025-01-07 17:50 UTC, korikuzma approved these changes

2025-01-07 17:53 UTC, merged